timezone: Europe/Rome
permalink: pretty
repository: trasparente/unita

# DEFAULTS
# type is optional, path is required for a scope/values pair.
defaults:
  - scope:
      path: ''
    values:
      layout: default
      default_class: remember-document
  - scope:
      path: ''
      type: posts
    values:
      pagination: true
      aside: true
      default_class: remember-document headings-anchor

# COLLECTIONS
collections:
  docs:
    title: Docs
    output: true
    sort_by: order
  maya:
    title: Maya
    output: true
    sort_by: order
  games:
    title: Games
    output: true
    sort_by: order
  posts:
    title: Posts

# OPTIONS defaults
#language: en
#direction: ltr
#soma: true