timezone: Europe/Rome
permalink: pretty
repository: trasparente/unita

# DEFAULTS
defaults:
  - scope:
      path: ''
    values:
      layout: default

# COLLECTIONS
collections:
  docs:
    title: Docs
    output: true
  posts:
    title: Posts

# OPTIONS defaults
#language: en
#direction: ltr