timezone: Europe/Rome
permalink: pretty
repository: trasparente/unita

# DEFAULTS
# type is optional, path is required for a scope/values pair.
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: posts
    values:
      pagination: true

# COLLECTIONS
collections:
  docs:
    title: Docs
    output: true
  flows:
    title: Flows
    output: true
  posts:
    title: Posts

# OPTIONS defaults
#language: en
#direction: ltr